#set_collection = {"charan",13,5,3}
#print(set_collection)
set_collection1 = set()
set_collection1.add(1)
set_collection1.add(2)
set_collection1.add(3)
set_collection1.add(4)
set_collection1.add(5)
set_collection1.remove(5)
set_collection1.pop()
print(set_collection1)